export const allCountriesFlags = [
  { name: "Brazil", code: "br" },
  { name: "Norway", code: "nor" },
  { name: "Argentina", code: "ar" },
  { name: "Andorra", code: "ad" },
  { name: "United Arab Emirates", code: "ae" },
  { name: "Afghanistan", code: "af" },
  { name: "Antigua and Barbuda", code: "ag" },
  { name: "Anguilla", code: "ai" },
  { name: "Albania", code: "al" },
  { name: "Armenia", code: "am" },
  { name: "Angola", code: "ao" },
  { name: "Antarctica", code: "aq" },
  { name: "Austria", code: "at" },
  { name: "Australia", code: "au" },
  { name: "Aruba", code: "AW" },
  { name: "Azerbaijan", code: "AZ" },
  { name: "Bosnia and Herzegovina", code: "BA" },
  { name: "Barbados", code: "BB" },
  { name: "Bangladesh", code: "BD" },
  { name: "Belgium", code: "BE" },
  { name: "Burkina Faso", code: "BF" },
  { name: "Bulgaria", code: "BG" },
  { name: "Bahrain", code: "BH" },
  { name: "Burundi", code: "BI" },

]