export const AllCountries = [
  { name: "Brazil" },
  { name: "Afghanistan" },
  { name: "Angola" },
  { name: "Albania" },
  { name: "United Arab Emirates" },
  { name: "Argentina" },
  { name: "Armenia" },
  { name: "Antarctica" },
  { name: "Antigua and Barbuda" },
  { name: "Australia" },
  { name: "Andorra" },
  { name: "Austria" },
  { name: "Azerbaijan" },
  { name: "Burundi" },
  { name: "Belgium" },
  { name: "Benin" },
  { name: "Burkina Faso" },
  { name: "Bangladesh" },
  { name: "Bulgaria" },
  { name: "Bahamas" },
  { name: "Bahrain" },
  { name: "Bosnia and Herz." },
  { name: "Belarus" },
  { name: "Belize" },
  { name: "Bolivia" },
  { name: "Brunei" },
  { name: "Bhutan" },
  { name: "Botswana" },
  { name: "Central African Rep." },
  { name: "Canada" },
  { name: "Switzerland" },
  { name: "Chile" },
  { name: "Cameroon" },
  { name: "China" },
  { name: "Côte d'Ivoire" },
  { name: "Dem. Rep. Congo" },
  { name: "Congo" },
  { name: "Colombia" },
  { name: "Costa Rica" },
  { name: "Cuba" },
  { name: "Cyprus" },
  { name: "Czechia" },
  { name: "Germany" },
  { name: "Djibouti" },
  { name: "Denmark" },
  { name: "Dominica" },
  { name: "Dominican Rep." },
  { name: "Algeria" },
  { name: "Ecuador" },
  { name: "Egypt" },
  { name: "Eritrea" },
  { name: "Spain" },
  { name: "Tonga" },
  { name: "Seychelles" },
  { name: "Estonia" },
  { name: "Ethiopia" },
  { name: "Finland" },
  { name: "Fiji" },
  { name: "France" },
  { name: "Gabon" },
  { name: "Georgia" },
  { name: "Ghana" },
  { name: "Guinea" },
  { name: "United Kingdom" },
  { name: "Gambia" },
  { name: "Guinea-Bissau" },
  { name: "Eq. Guinea" },
  { name: "Grenada" },
  { name: "St Vincent and the Grenadines" },
  { name: "Greece" },
  { name: "Greenland" },
  { name: "Guatemala" },
  { name: "Guyana" },
  { name: "Honduras" },
  { name: "Croatia" },
  { name: "Haiti" },
  { name: "Iran" },
  { name: "Hungary" },
  { name: "Tanzania" },
  { name: "Indonesia" },
  { name: "India" },
  { name: "Ireland" },
  { name: "Iraq" },
  { name: "Iceland" },
  { name: "Israel" },
  { name: "Italy" },
  { name: "Jamaica" },
  { name: "Jordan" },
  { name: "Japan" },
  { name: "Kazakhstan" },
  { name: "Kenya" },
  { name: "Kyrgyzstan" },
  { name: "Cambodia" },
  { name: "South Korea" },
  { name: "Kosovo" },
  { name: "Kuwait" },
  { name: "Laos" },
  { name: "Lebanon" },
  { name: "Liberia" },
  { name: "Libya" },
  { name: "Sri Lanka" },
  { name: "Lesotho" },
  { name: "Lithuania" },
  { name: "Liechtenstein" },
  { name: "Luxembourg" },
  { name: "Latvia" },
  { name: "Morocco" },
  { name: "Moldova" },
  { name: "Madagascar" },
  { name: "Marshall Islands" },
  { name: "Mexico" },
  { name: "Macedonia" },
  { name: "Mali" },
  { name: "Myanmar" },
  { name: "Montenegro" },
  { name: "Mongolia" },
  { name: "Monaco" },
  { name: "Mozambique" },
  { name: "Mauritania" },
  { name: "Mauritius" },
  { name: "Comoros" },
  { name: "Cabo Verde" },
  { name: "Singapore" },
  { name: "Kiribati" },
  { name: "Micronesia" },
  { name: "Malawi" },
  { name: "Malta" },
  { name: "Maldives" },
  { name: "Malaysia" },
  { name: "Barbados" },
  { name: "Namibia" },
  { name: "Niger" },
  { name: "Nigeria" },
  { name: "Nicaragua" },
  { name: "Netherlands" },
  { name: "Norway" },
  { name: "Nepal" },
  { name: "Palau" },
  { name: "Tuvalu" },
  { name: "Nauru" },
  { name: "Vatican" },
  { name: "New Zealand" },
  { name: "Oman" },
  { name: "Pakistan" },
  { name: "Panama" },
  { name: "Peru" },
  { name: "Philippines" },
  { name: "Papua New Guinea" },
  { name: "North Korea" },
  { name: "Poland" },
  { name: "Portugal" },
  { name: "Paraguay" },
  { name: "Palestine" },
  { name: "Qatar" },
  { name: "Romania" },
  { name: "Russia" },
  { name: "Rwanda" },
  { name: "Saudi Arabia" },
  { name: "San Marino" },
  { name: "Sudan" },
  { name: "Samoa" },
  { name: "Saint Kitts and Nevis" },
  { name: "Saint Lucia" },
  { name: "Sao Tome & Principe" },
  { name: "S. Sudan" },
  { name: "Senegal" },
  { name: "Solomon Is." },
  { name: "Sierra Leone" },
  { name: "El Salvador" },
  { name: "Somalia" },
  { name: "Serbia" },
  { name: "Suriname" },
  { name: "Slovakia" },
  { name: "Slovenia" },
  { name: "Sweden" },
  { name: "Swaziland" },
  { name: "Syria" },
  { name: "Chad" },
  { name: "Togo" },
  { name: "Thailand" },
  { name: "Tajikistan" },
  { name: "Turkmenistan" },
  { name: "Timor-leste" },
  { name: "Trinidad and Tobago" },
  { name: "Tunisia" },
  { name: "Turkey" },
  { name: "Taiwan" },
  { name: "Uganda" },
  { name: "Ukraine" },
  { name: "Uruguay" },
  { name: "United States of America" },
  { name: "Uzbekistan" },
  { name: "Venezuela" },
  { name: "Vietnam" },
  { name: "Vanuatu" },
  { name: "Yemen" },
  { name: "South Africa" },
  { name: "Zambia" },
  { name: "Zimbabwe" },
]