export const allCountriesFlags = [
  { name: "Brazil", code: "br", found: false },
  { name: "Norway", code: "no", found: false },
  { name: "Argentina", code: "ar", found: false },
  { name: "Andorra", code: "ad", found: false },
  { name: "United Arab Emirates", code: "ae", found: false },
  { name: "Afghanistan", code: "af", found: false },
  { name: "Antigua and Barbuda", code: "ag", found: false },
  { name: "Albania", code: "al", found: false },
  { name: "Armenia", code: "am", found: false },
  { name: "Angola", code: "ao", found: false },
  { name: "Antarctica", code: "aq", found: false },
  { name: "Austria", code: "at", found: false },
  { name: "Australia", code: "au", found: false },
  { name: "Aruba", code: "AW", found: false },
  { name: "Azerbaijan", code: "AZ", found: false },
  { name: "Bosnia and Herzegovina", code: "BA", found: false },
  { name: "Barbados", code: "BB", found: false },
  { name: "Bangladesh", code: "BD", found: false },
  { name: "Belgium", code: "BE", found: false },
  { name: "Burkina Faso", code: "BF", found: false },
  { name: "Bulgaria", code: "BG", found: false },
  { name: "Bahrain", code: "BH", found: false },
  { name: "Burundi", code: "BI", found: false },
  { name: "Benin", code: "bj", found: false },
  { name: "Bahamas", code: "bs", found: false },
  { name: "Belarus", code: "by", found: false },
  { name: "Belize", code: "bz", found: false },
  { name: "Bolivia", code: "bo", found: false },
  { name: "Brunei", code: "bn", found: false },
  { name: "Bhutan", code: "bt", found: false },
  { name: "Botswana", code: "bw", found: false },
  { name: "Central African Republic", code: "cf", found: false },
  { name: "Canada", code: "ca", found: false },
  { name: "Switzerland", code: "ch", found: false },
  { name: "Chile", code: "cl", found: false },
  { name: "Cameroon", code: "cm", found: false },
  { name: "China", code: "cn", found: false },
  { name: "Côted'Ivoire", code: "ci", found: false },
  { name: "Democratic Republic of the Congo", code: "cd", found: false },
  { name: "Congo", code: "cg", found: false },
  { name: "Colombia", code: "co", found: false },
  { name: "Costa Rica", code: "cr", found: false },
  { name: "Cuba", code: "cu", found: false },
  { name: "Cyprus", code: "cy", found: false },
  { name: "Czech Republic", code: "cz", found: false },
  { name: "Germany", code: "de", found: false },
  { name: "Djibouti", code: "dj", found: false },
  { name: "denmark", code: "dk", found: false },
  { name: "Dominica", code: "dm", found: false },
  { name: "Dominican Republic", code: "do", found: false },
  { name: "Algeria", code: "dz", found: false },
  { name: "Ecuador", code: "ec", found: false },
  { name: "Egypt", code: "eg", found: false },
  { name: "Eritrea", code: "er", found: false },
  { name: "Spain", code: "es", found: false },
  { name: "Tonga", code: "to", found: false },
  { name: "Seychelles", code: "sc", found: false },
  { name: "Estonia", code: "ee", found: false },
  { name: "Ethiopia", code: "et", found: false },
  { name: "Finland", code: "fi", found: false },
  { name: "Fiji", code: "fj", found: false },
  { name: "France", code: "fr", found: false },
  { name: "Gabon", code: "ga", found: false },
  { name: "Georgia", code: "ge", found: false },
  { name: "Ghana", code: "gh", found: false },
  { name: "Guinea", code: "gn", found: false },
  { name: "United Kingdom", code: "gb", found: false },
  { name: "Gambia", code: "gm", found: false },
  { name: "Guinea-Bissau", code: "gw", found: false },
  { name: "Equatorial Guinea", code: "gq", found: false },
  { name: "Grenada", code: "gd", found: false },
  { name: "St Vincent and The Grenadines", code: "vc", found: false },
  { name: "Greece", code: "gr", found: false },
  { name: "Greenland", code: "gl", found: false },
  { name: "Guatemala", code: "gt", found: false },
  { name: "Guyana", code: "gy", found: false },
  { name: "Honduras", code: "hn", found: false },
  { name: "Croatia", code: "hr", found: false },
  { name: "Haiti", code: "ht", found: false },
  { name: "Hungary", code: "hu", found: false },
  { name: "Singapore", code: "sg", found: false },
  { name: "Indonesia", code: "id", found: false },
  { name: "India", code: "in", found: false },
  { name: "Ireland", code: "ie", found: false },
  { name: "Iraq", code: "iq", found: false },
  { name: "Iran", code: "ir", found: false },
  { name: "Iceland", code: "is", found: false },
  { name: "Israel", code: "il", found: false },
  { name: "Italy", code: "it", found: false },
  { name: "Jamaica", code: "jm", found: false },
  { name: "Jordan", code: "jo", found: false },
  { name: "Japan", code: "jp", found: false },
  { name: "Kazakhstan", code: "kz", found: false },
  { name: "Kenya", code: "ke", found: false },
  { name: "Kyrgyzstan", code: "kg", found: false },
  { name: "Cambodia", code: "kh", found: false },
  { name: "South Korea", code: "kr", found: false },
  { name: "Kosovo", code: "xk", found: false },
  { name: "Kuwait", code: "kw", found: false },
  { name: "Laos", code: "la", found: false },
  { name: "Lebanon", code: "lb", found: false },
  { name: "Liberia", code: "lr", found: false },
  { name: "Libya", code: "ly", found: false },
  { name: "Sri Lanka", code: "lk", found: false },
  { name: "Lesotho", code: "ls", found: false },
  { name: "Lithuania", code: "lt", found: false },
  { name: "Liechtenstein", code: "li", found: false },
  { name: "Luxembourg", code: "lu", found: false },
  { name: "Latvia", code: "lv", found: false },
  { name: "Morocco", code: "ma", found: false },
  { name: "Moldova", code: "md", found: false },
  { name: "Madagascar", code: "mg", found: false },
  { name: "Marshall Islands", code: "mh", found: false },
  { name: "Mexico", code: "mx", found: false },
  { name: "Macedonia", code: "mk", found: false },
  { name: "Mali", code: "ml", found: false },
  { name: "Myanmar", code: "mm", found: false },
  { name: "Montenegro", code: "me", found: false },
  { name: "Mongolia", code: "mn", found: false },
  { name: "Monaco", code: "mc", found: false },
  { name: "Mozambique", code: "mz", found: false },
  { name: "Mauritania", code: "mr", found: false },
  { name: "Mauritius", code: "mu", found: false },
  { name: "Comoros", code: "km", found: false },
  { name: "Cabo Verde", code: "cv", found: false },
  { name: "Kiribati", code: "ki", found: false },
  { name: "Micronesia", code: "fm", found: false },
  { name: "Malawi", code: "mw", found: false },
  { name: "Malta", code: "mt", found: false },
  { name: "Maldives", code: "mv", found: false },
  { name: "Malaysia", code: "my", found: false },
  { name: "Namibia", code: "na", found: false },
  { name: "Niger", code: "ne", found: false },
  { name: "Nigeria", code: "ng", found: false },
  { name: "Nicaragua", code: "ni", found: false },
  { name: "Netherlands", code: "nl", found: false },
  { name: "Nepal", code: "np", found: false },
  { name: "Palau", code: "pw", found: false },
  { name: "Tuvalu", code: "tv", found: false },
  { name: "Nauru", code: "nr", found: false },
  { name: "Vatican City", code: "va", found: false },
  { name: "New Zealand", code: "nz", found: false },
  { name: "Oman", code: "om", found: false },
  { name: "Pakistan", code: "pk", found: false },
  { name: "Tanzania", code: "tz", found: false },
  { name: "Panama", code: "pa", found: false },
  { name: "Peru", code: "pe", found: false },
  { name: "Philippines", code: "ph", found: false },
  { name: "Papua New Guinea", code: "pg", found: false },
  { name: "North Korea", code: "kp", found: false },
  { name: "Poland", code: "pl", found: false },
  { name: "Portugal", code: "pt", found: false },
  { name: "Paraguay", code: "py", found: false },
  { name: "Palestine", code: "ps", found: false },
  { name: "Qatar", code: "qa", found: false },
  { name: "Romenia", code: "ro", found: false },
  { name: "Russia", code: "ru", found: false },
  { name: "Rwanda", code: "rw", found: false },
  { name: "Saudi Arabia", code: "sa", found: false },
  { name: "San Marino", code: "sm", found: false },
  { name: "Sudan", code: "sd", found: false },
  { name: "Samoa", code: "ws", found: false },
  { name: "St Kitts and Nevis", code: "kn", found: false },
  { name: "Saint Lucia", code: "lc", found: false },
  { name: "Sao Tome and Principe", code: "st", found: false },
  { name: "South Sudan", code: "ss", found: false },
  { name: "Senegal", code: "sn", found: false },
  { name: "Solomon Islands", code: "sb", found: false },
  { name: "Sierra Leone", code: "sl", found: false },
  { name: "El Salvador", code: "sv", found: false },
  { name: "Somalia", code: "so", found: false },
  { name: "Serbia", code: "rs", found: false },
  { name: "Suriname", code: "sr", found: false },
  { name: "Slovakia", code: "sk", found: false },
  { name: "Slovenia", code: "si", found: false },
  { name: "Sweden", code: "se", found: false },
  { name: "Swaziland", code: "sz", found: false },
  { name: "Syria", code: "sy", found: false },
  { name: "Chad", code: "td", found: false },
  { name: "Togo", code: "tg", found: false },
  { name: "Thailand", code: "th", found: false },
  { name: "Tajikistan", code: "tj", found: false },
  { name: "Turkmenistan", code: "tm", found: false },
  { name: "Timor-lest", code: "tl", found: false },
  { name: "Trinidad and Tobago", code: "tt", found: false },
  { name: "Tunisia", code: "tn", found: false },
  { name: "Turkey", code: "tr", found: false },
  { name: "Taiwan", code: "tw", found: false },
  { name: "Uganda", code: "ug", found: false },
  { name: "Ukraine", code: "ua", found: false },
  { name: "Uruguay", code: "uy", found: false },
  { name: "United States", code: "us", found: false },
  { name: "Uzbekistan", code: "uz", found: false },
  { name: "Venezuela", code: "ve", found: false },
  { name: "Vietnam", code: "vn", found: false },
  { name: "Vanuatu", code: "vu", found: false },
  { name: "Yemen", code: "ye", found: false },
  { name: "South Africa", code: "za", found: false },
  { name: "Zambia", code: "zm", found: false },
  { name: "Zimbabwe", code: "zw", found: false },
]