export const AllCountries = [
  { name: "Brazil", continent: "world south-america" },
  { name: "Afghanistan", continent: "world asia" },
  { name: "Angola", continent: "world africa" },
  { name: "Albania", continent: "world europe" },
  { name: "United Arab Emirates", continent: "world asia" },
  { name: "Argentina", continent: "world south-america" },
  { name: "Armenia", continent: "world europe" },
  { name: "Antarctica", continent: "world " },
  { name: "Antigua and Barbuda", continent: "world north-america" },
  { name: "Australia", continent: "world oceania" },
  { name: "Andorra", continent: "world europe" },
  { name: "Austria", continent: "world europe" },
  { name: "Azerbaijan", continent: "world europe asia" },
  { name: "Burundi", continent: "world africa" },
  { name: "Belgium", continent: "world europe" },
  { name: "Benin", continent: "world africa" },
  { name: "Burkina Faso", continent: "world africa" },
  { name: "Bangladesh", continent: "world asia" },
  { name: "Bulgaria", continent: "world europe" },
  { name: "Bahamas", continent: "world north-america" },
  { name: "Bahrain", continent: "world asia" },
  { name: "Bosnia and Herz.", continent: "world europe" },
  { name: "Belarus", continent: "world europe" },
  { name: "Belize", continent: "world north-america" },
  { name: "Bolivia", continent: "world south-america" },
  { name: "Brunei", continent: "world asia" },
  { name: "Bhutan", continent: "world asia" },
  { name: "Botswana", continent: "world africa" },
  { name: "Central African Rep.", continent: "world africa" },
  { name: "Canada", continent: "world north-america" },
  { name: "Switzerland", continent: "world europe" },
  { name: "Chile", continent: "world south-america" },
  { name: "Cameroon", continent: "world africa" },
  { name: "China", continent: "world asia" },
  { name: "Côte d'Ivoire", continent: "world africa" },
  { name: "Dem. Rep. Congo", continent: "world africa" },
  { name: "Congo", continent: "world africa" },
  { name: "Colombia", continent: "world south-america" },
  { name: "Costa Rica", continent: "world north-america" },
  { name: "Cuba", continent: "world north-america" },
  { name: "Cyprus", continent: "world europe" },
  { name: "Czechia", continent: "world europe" },
  { name: "Germany", continent: "world europe" },
  { name: "Djibouti", continent: "world africa" },
  { name: "Denmark", continent: "world europe" },
  { name: "Dominica", continent: "world north-america" },
  { name: "Dominican Rep.", continent: "world north-america" },
  { name: "Algeria", continent: "world africa" },
  { name: "Ecuador", continent: "world south-america" },
  { name: "Egypt", continent: "world africa" },
  { name: "Eritrea", continent: "world africa" },
  { name: "Spain", continent: "world europe" },
  { name: "Tonga", continent: "world oceania" },
  { name: "Seychelles", continent: "world africa" },
  { name: "Estonia", continent: "world europe" },
  { name: "Ethiopia", continent: "world africa" },
  { name: "Finland", continent: "world europe" },
  { name: "Fiji", continent: "world oceania" },
  { name: "France", continent: "world europe" },
  { name: "Gabon", continent: "world africa" },
  { name: "Georgia", continent: "world europe" },
  { name: "Ghana", continent: "world africa" },
  { name: "Guinea", continent: "world africa" },
  { name: "United Kingdom", continent: "world europe" },
  { name: "Gambia", continent: "world africa" },
  { name: "Guinea-Bissau", continent: "world africa" },
  { name: "Eq. Guinea", continent: "world africa" },
  { name: "Grenada", continent: "world north-america" },
  { name: "St Vincent and the Grenadines", continent: "world north-america" },
  { name: "Greece", continent: "world europe" },
  { name: "Greenland", continent: "world north-america" },
  { name: "Guatemala", continent: "world north-america" },
  { name: "Guyana", continent: "world south-america" },
  { name: "Honduras", continent: "world north-america" },
  { name: "Croatia", continent: "world europe" },
  { name: "Haiti", continent: "world north-america" },
  { name: "Iran", continent: "world asia" },
  { name: "Hungary", continent: "world europe" },
  { name: "Tanzania", continent: "world africa" },
  { name: "Indonesia", continent: "world asia" },
  { name: "India", continent: "world asia" },
  { name: "Ireland", continent: "world europe" },
  { name: "Iraq", continent: "world asia" },
  { name: "Iceland", continent: "world europe" },
  { name: "Israel", continent: "world asia" },
  { name: "Italy", continent: "world europe" },
  { name: "Jamaica", continent: "world north-america" },
  { name: "Jordan", continent: "world asia" },
  { name: "Japan", continent: "world asia" },
  { name: "Kazakhstan", continent: "world europe asia" },
  { name: "Kenya", continent: "world africa" },
  { name: "Kyrgyzstan", continent: "world asia" },
  { name: "Cambodia", continent: "world asia" },
  { name: "South Korea", continent: "world asia" },
  { name: "Kosovo", continent: "world europe" },
  { name: "Kuwait", continent: "world europe" },
  { name: "Laos", continent: "world asia" },
  { name: "Lebanon", continent: "world asia" },
  { name: "Liberia", continent: "world africa" },
  { name: "Libya", continent: "world africa" },
  { name: "Sri Lanka", continent: "world asia" },
  { name: "Lesotho", continent: "world africa" },
  { name: "Lithuania", continent: "world europe" },
  { name: "Liechtenstein", continent: "world europe" },
  { name: "Luxembourg", continent: "world europe" },
  { name: "Latvia", continent: "world europe" },
  { name: "Morocco", continent: "world africa" },
  { name: "Moldova", continent: "world europe" },
  { name: "Madagascar", continent: "world africa" },
  { name: "Marshall Islands", continent: "world oceania" },
  { name: "Mexico", continent: "world north-america" },
  { name: "Macedonia", continent: "world europe" },
  { name: "Mali", continent: "world africa" },
  { name: "Myanmar", continent: "world asia" },
  { name: "Montenegro", continent: "world europe" },
  { name: "Mongolia", continent: "world asia" },
  { name: "Monaco", continent: "world europe" },
  { name: "Mozambique", continent: "world africa" },
  { name: "Mauritania", continent: "world africa" },
  { name: "Mauritius", continent: "world africa" },
  { name: "Comoros", continent: "world africa" },
  { name: "Cabo Verde", continent: "world africa" },
  { name: "Singapore", continent: "world asia" },
  { name: "Kiribati", continent: "world oceania" },
  { name: "Micronesia", continent: "world oceania" },
  { name: "Malawi", continent: "world africa" },
  { name: "Malta", continent: "world europe" },
  { name: "Maldives", continent: "world asia" },
  { name: "Malaysia", continent: "world asia" },
  { name: "Barbados", continent: "world north-america" },
  { name: "Namibia", continent: "world africa" },
  { name: "Niger", continent: "world africa" },
  { name: "Nigeria", continent: "world africa" },
  { name: "Nicaragua", continent: "world north-america" },
  { name: "Netherlands", continent: "world europe" },
  { name: "Norway", continent: "world europe" },
  { name: "Nepal", continent: "world asia" },
  { name: "Palau", continent: "world oceania" },
  { name: "Tuvalu", continent: "world oceania" },
  { name: "Nauru", continent: "world oceania" },
  { name: "Vatican", continent: "world europe" },
  { name: "New Zealand", continent: "world oceania" },
  { name: "Oman", continent: "world asia" },
  { name: "Pakistan", continent: "world asia" },
  { name: "Panama", continent: "world north-america" },
  { name: "Peru", continent: "world south-america" },
  { name: "Philippines", continent: "world asia" },
  { name: "Papua New Guinea", continent: "world oceania" },
  { name: "North Korea", continent: "world asia" },
  { name: "Poland", continent: "world europe" },
  { name: "Portugal", continent: "world europe" },
  { name: "Paraguay", continent: "world south-america" },
  { name: "Palestine", continent: "world asia" },
  { name: "Qatar", continent: "world asia" },
  { name: "Romania", continent: "world europe" },
  { name: "Russia", continent: "world europe asia" },
  { name: "Rwanda", continent: "world africa" },
  { name: "Saudi Arabia", continent: "world asia" },
  { name: "San Marino", continent: "world europe" },
  { name: "Sudan", continent: "world africa" },
  { name: "Samoa", continent: "world oceania" },
  { name: "Saint Kitts and Nevis", continent: "world north-america" },
  { name: "Saint Lucia", continent: "world north-america" },
  { name: "Sao Tome & Principe", continent: "world africa" },
  { name: "S. Sudan", continent: "world africa" },
  { name: "Senegal", continent: "world africa" },
  { name: "Solomon Is.", continent: "world oceania" },
  { name: "Sierra Leone", continent: "world africa" },
  { name: "El Salvador", continent: "world north-america" },
  { name: "Somalia", continent: "world africa" },
  { name: "Serbia", continent: "world europe" },
  { name: "Suriname", continent: "world south-america" },
  { name: "Slovakia", continent: "world europe" },
  { name: "Slovenia", continent: "world europe" },
  { name: "Sweden", continent: "world europe" },
  { name: "Swaziland", continent: "world africa" },
  { name: "Syria", continent: "world asia" },
  { name: "Chad", continent: "world africa" },
  { name: "Togo", continent: "world africa" },
  { name: "Thailand", continent: "world asia" },
  { name: "Tajikistan", continent: "world asia" },
  { name: "Turkmenistan", continent: "world asia" },
  { name: "Timor-leste", continent: "world asia" },
  { name: "Trinidad and Tobago", continent: "world south-america" },
  { name: "Tunisia", continent: "world africa" },
  { name: "Turkey", continent: "world europe asia" },
  { name: "Taiwan", continent: "world asia" },
  { name: "Uganda", continent: "world africa" },
  { name: "Ukraine", continent: "world europe" },
  { name: "Uruguay", continent: "world south-america" },
  { name: "United States of America", continent: "world north-america" },
  { name: "Uzbekistan", continent: "world asia" },
  { name: "Venezuela", continent: "world south-america" },
  { name: "Vietnam", continent: "world asia" },
  { name: "Vanuatu", continent: "world oceania" },
  { name: "Yemen", continent: "world asia" },
  { name: "South Africa", continent: "world africa" },
  { name: "Zambia", continent: "world africa" },
  { name: "Zimbabwe", continent: "world africa" },
]